In [1]:
import numpy as np

In [11]:
# зарплаты
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [12]:
# кредитный скоринг
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [13]:
# посчитаем ковариацию "вручную"
cov1 = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov1

9157.839999999997

In [14]:
# при помощи библиотечной функции
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [15]:
# Они совпали

In [17]:
# стандартное отклонение зарплаты
zp_std = np.std(zp, ddof=0)
zp_std

59.115480206118605

In [18]:
# стандартное отклонение кредитного скоринга
ks_std = np.std(ks, ddof=0)
ks_std

174.55340157098058

In [20]:
# посчитаем корреляцию "вручную"
corr1 = cov1/(zp_std*ks_std)
corr1

0.8874900920739158

In [21]:
# проверим библиотечной функцией
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [22]:
# они совпали